
#This is a template to build your own project with the e-puck2_main-processor folder as a library.
#Simply adapt the lines below to be able to compile

# Define project name here
PROJECT = project

#Define path to the e-puck2_main-processor folder
GLOBAL_PATH = ../../lib/e-puck2_main-processor

#Source files to include
CSRC += ./main.c \
		./pi_regulator.c \
		./process_image.c \

#Header folders to include
INCDIR += 

#For debugging (is there a "cleaner" way to do it?)
USE_OPT += -O0 -g

#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile
